### ISSUE TITLE
zero type of plugin.MetricType returned for all collected metrics

### ISSUE THREAD

**Issue by woodsaj** [intelsdi-x/snap-plugin-collector-elasticsearch#9]
steps to reproduce.

1) start up snap with elasticsearch plugin configured
```
---
log_level: 1
control:
  plugin_trust_level: 0
  plugins:
    collector:
      elasticsearch:
        all:
          server: 127.0.0.1
          port: 9200
```
2) create task to collect metrics
```
curl -X POST http://localhost:8181/v1/tasks -d '{
  "name": "es-test",
  "start": true,
  "workflow": {
    "collect": {
      "metrics": {
        "/intel/elasticsearch/*": {}
      }
    }
  },
  "schedule": {
    "type": "simple",
    "interval": "10s"
  }
}'
```
3) watch task

All data is the zero type of plugin.MetricType
```
data: {"type":"stream-open","message":"Stream opened"}

data: {"type":"metric-event","message":"","event":[{"namespace":"/","data":null,"timestamp":"0001-01-01T00:00:00Z","tags":{"plugin_running_on":"anthony-desktop"}},
...
```
